# Generated by Django 3.2.7 on 2021-11-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellerinf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='cs',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
    ]
